# Product configuration
product_name: "TrackJammer MIDI Sequencer"
title: "TrackJammer MIDI Sequencer"
description: Ready to unlock the creative potential of your Launchpad?
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark


url: https://eclipsinglines.github.io/trackjammer-user-manual/

# Enable back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable GitHub Pages plugins
plugins:
  - jekyll-seo-tag

# Navigation structure
nav_sort: case_insensitive

# Footer content
footer_content: "Copyright &copy; 2025 Track Jammer. Distributed by an <a href=\"https://github.com/eclipsinglines/trackjammer-user-manual/tree/main/LICENSE\">MIT license.</a>"

# External links
aux_links:
  "Get on Gumroad":
    - "https://eclipsinglines.gumroad.com/l/TracksJammerLE"

callouts:
  generative:
    title: GENERATIVE ACTION!
    color: red
  note:
    title: Note
    color: blue

