title: Tack Jammer MIDI Sequencer - User Manual
description: Ready to unlock the creative potential of your Launchpad?
theme: just-the-docs

url: https://eclipsinglines.github.io/trackjammer-user-manual/

aux_links:
  Template Repository: https://eclipsinglines.github.io/trackjammer-user-manual/
